const actionTypes = {
    DELETE_USER: 'DELETE_USER',
    CREATE_USER_RAMDOM: 'CREATE_USER_RAMDOM',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',

    READ_USER: 'READ_USER',

    EDIT_USER: 'EDIT_USER'
}

export default actionTypes;